import { GroupAgentLink } from './group-agent-links.types';

/**
 * Bootstrap dataset for `GroupAgentLinksStore`.
 *
 * Generated once via `tools/generate-link-seed.mjs` from the legacy
 * combined seeds (`Agent.channels` + `Agent.groups[].active` ×
 * `Group.assignedAgents`). The legacy fields are now removed from
 * `Agent` and `Group`, and this constant is the single source of
 * truth for "who is in which group, with which channels, on or
 * paused" for first-boot or after-reset.
 *
 * Each row is `{ agentId, groupId, channels, active }`. Channels are
 * already clamped to the parent group's channel offering (you cannot
 * enable `chat` for an agent in a phone-only group).
 */
export const GROUP_AGENT_LINKS_SEED: readonly GroupAgentLink[] = [
  { agentId: 1, groupId: 1, channels: ['phone'], active: true },
  { agentId: 1, groupId: 2, channels: ['phone'], active: true },
  { agentId: 1, groupId: 3, channels: ['phone'], active: true },
  { agentId: 1, groupId: 4, channels: ['phone'], active: true },
  { agentId: 1, groupId: 5, channels: ['phone'], active: true },
  { agentId: 1, groupId: 6, channels: ['phone'], active: true },
  { agentId: 1, groupId: 9, channels: ['phone'], active: true },
  { agentId: 1, groupId: 10, channels: ['phone'], active: true },
  { agentId: 1, groupId: 11, channels: ['phone'], active: true },
  { agentId: 1, groupId: 12, channels: ['phone'], active: true },
  { agentId: 1, groupId: 13, channels: ['phone'], active: true },
  { agentId: 1, groupId: 14, channels: ['phone'], active: true },
  { agentId: 2, groupId: 1, channels: ['phone'], active: true },
  { agentId: 2, groupId: 2, channels: ['phone'], active: true },
  { agentId: 2, groupId: 3, channels: ['phone'], active: true },
  { agentId: 2, groupId: 4, channels: ['phone'], active: true },
  { agentId: 2, groupId: 5, channels: ['phone'], active: true },
  { agentId: 2, groupId: 8, channels: ['phone'], active: true },
  { agentId: 2, groupId: 9, channels: ['phone'], active: true },
  { agentId: 2, groupId: 10, channels: ['phone'], active: true },
  { agentId: 2, groupId: 11, channels: ['phone'], active: true },
  { agentId: 2, groupId: 12, channels: ['phone'], active: true },
  { agentId: 2, groupId: 13, channels: ['phone'], active: true },
  { agentId: 2, groupId: 14, channels: ['phone'], active: true },
  { agentId: 3, groupId: 1, channels: ['phone'], active: true },
  { agentId: 3, groupId: 2, channels: ['phone'], active: true },
  { agentId: 3, groupId: 4, channels: ['phone'], active: true },
  { agentId: 3, groupId: 5, channels: ['phone'], active: true },
  { agentId: 3, groupId: 6, channels: ['phone'], active: true },
  { agentId: 3, groupId: 8, channels: ['phone'], active: true },
  { agentId: 3, groupId: 9, channels: ['phone'], active: true },
  { agentId: 3, groupId: 10, channels: ['phone', 'chat'], active: true },
  { agentId: 3, groupId: 11, channels: ['phone', 'chat'], active: true },
  { agentId: 3, groupId: 12, channels: ['phone', 'chat'], active: true },
  { agentId: 3, groupId: 13, channels: ['phone', 'chat'], active: true },
  { agentId: 3, groupId: 14, channels: ['phone'], active: true },
  { agentId: 4, groupId: 1, channels: ['phone'], active: true },
  { agentId: 4, groupId: 4, channels: ['phone'], active: true },
  { agentId: 4, groupId: 8, channels: ['phone'], active: true },
  { agentId: 4, groupId: 12, channels: ['phone', 'chat'], active: true },
  { agentId: 5, groupId: 1, channels: ['phone'], active: true },
  { agentId: 5, groupId: 3, channels: ['phone'], active: true },
  { agentId: 5, groupId: 4, channels: ['phone'], active: true },
  { agentId: 5, groupId: 5, channels: ['phone'], active: true },
  { agentId: 5, groupId: 8, channels: ['phone'], active: true },
  { agentId: 5, groupId: 9, channels: ['phone'], active: true },
  { agentId: 5, groupId: 11, channels: ['phone'], active: true },
  { agentId: 5, groupId: 12, channels: ['phone'], active: true },
  { agentId: 5, groupId: 13, channels: ['phone'], active: true },
  { agentId: 5, groupId: 14, channels: ['phone'], active: true },
  { agentId: 6, groupId: 1, channels: ['phone'], active: true },
  { agentId: 6, groupId: 3, channels: ['phone'], active: true },
  { agentId: 6, groupId: 4, channels: ['phone'], active: false },
  { agentId: 6, groupId: 5, channels: ['phone'], active: true },
  { agentId: 6, groupId: 7, channels: ['phone'], active: true },
  { agentId: 6, groupId: 8, channels: ['phone'], active: true },
  { agentId: 6, groupId: 9, channels: ['phone'], active: true },
  { agentId: 6, groupId: 10, channels: ['phone'], active: true },
  { agentId: 6, groupId: 11, channels: ['phone'], active: true },
  { agentId: 6, groupId: 12, channels: ['phone'], active: true },
  { agentId: 6, groupId: 13, channels: ['phone'], active: true },
  { agentId: 6, groupId: 14, channels: ['phone'], active: true },
  { agentId: 7, groupId: 1, channels: ['phone'], active: true },
  { agentId: 7, groupId: 2, channels: ['phone', 'email'], active: true },
  { agentId: 7, groupId: 3, channels: ['phone'], active: true },
  { agentId: 7, groupId: 4, channels: ['phone'], active: true },
  { agentId: 7, groupId: 5, channels: ['phone'], active: true },
  { agentId: 7, groupId: 7, channels: ['phone'], active: true },
  { agentId: 7, groupId: 9, channels: ['phone'], active: true },
  { agentId: 7, groupId: 10, channels: ['phone', 'chat'], active: true },
  { agentId: 7, groupId: 11, channels: ['phone', 'chat', 'email'], active: true },
  { agentId: 7, groupId: 12, channels: ['phone', 'chat'], active: true },
  { agentId: 7, groupId: 13, channels: ['phone', 'chat'], active: true },
  { agentId: 7, groupId: 14, channels: ['phone'], active: true },
  { agentId: 8, groupId: 1, channels: ['phone'], active: true },
  { agentId: 8, groupId: 2, channels: ['phone'], active: true },
  { agentId: 8, groupId: 3, channels: ['phone'], active: true },
  { agentId: 8, groupId: 4, channels: ['phone'], active: true },
  { agentId: 8, groupId: 5, channels: ['phone'], active: true },
  { agentId: 8, groupId: 7, channels: ['phone'], active: true },
  { agentId: 8, groupId: 9, channels: ['phone'], active: true },
  { agentId: 8, groupId: 10, channels: ['phone', 'chat'], active: true },
  { agentId: 8, groupId: 11, channels: ['phone', 'chat'], active: true },
  { agentId: 8, groupId: 12, channels: ['phone', 'chat'], active: true },
  { agentId: 8, groupId: 13, channels: ['phone', 'chat'], active: true },
  { agentId: 8, groupId: 14, channels: ['phone'], active: true },
  { agentId: 9, groupId: 1, channels: ['phone'], active: true },
  { agentId: 9, groupId: 3, channels: ['phone'], active: false },
  { agentId: 9, groupId: 4, channels: ['phone'], active: true },
  { agentId: 9, groupId: 5, channels: ['phone'], active: true },
  { agentId: 9, groupId: 8, channels: ['phone'], active: false },
  { agentId: 9, groupId: 9, channels: ['phone'], active: true },
  { agentId: 9, groupId: 10, channels: ['phone'], active: true },
  { agentId: 9, groupId: 11, channels: ['phone'], active: true },
  { agentId: 9, groupId: 12, channels: ['phone'], active: true },
  { agentId: 9, groupId: 13, channels: ['phone'], active: true },
  { agentId: 9, groupId: 14, channels: ['phone'], active: true },
  { agentId: 10, groupId: 2, channels: ['phone'], active: true },
  { agentId: 10, groupId: 4, channels: ['phone'], active: true },
  { agentId: 10, groupId: 5, channels: ['phone'], active: true },
  { agentId: 10, groupId: 8, channels: ['phone'], active: true },
  { agentId: 10, groupId: 9, channels: ['phone'], active: true },
  { agentId: 10, groupId: 12, channels: ['phone', 'chat'], active: true },
  { agentId: 10, groupId: 13, channels: ['phone', 'chat'], active: true },
  { agentId: 11, groupId: 1, channels: ['phone'], active: true },
  { agentId: 11, groupId: 3, channels: ['phone'], active: true },
  { agentId: 11, groupId: 5, channels: ['phone'], active: true },
  { agentId: 11, groupId: 9, channels: ['phone'], active: true },
  { agentId: 11, groupId: 11, channels: ['phone'], active: true },
  { agentId: 11, groupId: 12, channels: ['phone'], active: true },
  { agentId: 11, groupId: 13, channels: ['phone'], active: true },
  { agentId: 12, groupId: 1, channels: ['phone'], active: true },
  { agentId: 12, groupId: 2, channels: ['phone'], active: true },
  { agentId: 12, groupId: 3, channels: ['phone'], active: true },
  { agentId: 12, groupId: 4, channels: ['phone'], active: true },
  { agentId: 12, groupId: 5, channels: ['phone'], active: true },
  { agentId: 12, groupId: 6, channels: ['phone'], active: true },
  { agentId: 12, groupId: 8, channels: ['phone'], active: true },
  { agentId: 12, groupId: 9, channels: ['phone'], active: true },
  { agentId: 12, groupId: 10, channels: ['phone'], active: true },
  { agentId: 12, groupId: 11, channels: ['phone'], active: true },
  { agentId: 12, groupId: 12, channels: ['phone'], active: true },
  { agentId: 12, groupId: 13, channels: ['phone'], active: true },
  { agentId: 12, groupId: 14, channels: ['phone'], active: true },
  { agentId: 13, groupId: 1, channels: ['phone'], active: true },
  { agentId: 13, groupId: 2, channels: ['phone'], active: true },
  { agentId: 13, groupId: 3, channels: ['phone'], active: true },
  { agentId: 13, groupId: 4, channels: ['phone'], active: true },
  { agentId: 13, groupId: 5, channels: ['phone'], active: true },
  { agentId: 13, groupId: 8, channels: ['phone'], active: true },
  { agentId: 13, groupId: 9, channels: ['phone'], active: true },
  { agentId: 13, groupId: 10, channels: ['phone', 'chat'], active: true },
  { agentId: 13, groupId: 11, channels: ['phone', 'chat'], active: true },
  { agentId: 13, groupId: 12, channels: ['phone', 'chat'], active: true },
  { agentId: 13, groupId: 13, channels: ['phone', 'chat'], active: true },
  { agentId: 13, groupId: 14, channels: ['phone'], active: true },
  { agentId: 14, groupId: 2, channels: ['phone'], active: true },
  { agentId: 14, groupId: 3, channels: ['phone'], active: true },
  { agentId: 14, groupId: 5, channels: ['phone'], active: true },
  { agentId: 14, groupId: 8, channels: ['phone'], active: true },
  { agentId: 14, groupId: 9, channels: ['phone'], active: true },
  { agentId: 14, groupId: 11, channels: ['phone'], active: true },
  { agentId: 14, groupId: 12, channels: ['phone'], active: true },
  { agentId: 14, groupId: 13, channels: ['phone'], active: true },
  { agentId: 15, groupId: 2, channels: ['phone'], active: true },
  { agentId: 15, groupId: 3, channels: ['phone'], active: true },
  { agentId: 15, groupId: 4, channels: ['phone'], active: true },
  { agentId: 15, groupId: 6, channels: ['phone'], active: true },
  { agentId: 15, groupId: 8, channels: ['phone'], active: true },
  { agentId: 15, groupId: 10, channels: ['phone', 'chat'], active: true },
  { agentId: 15, groupId: 11, channels: ['phone', 'chat'], active: true },
  { agentId: 15, groupId: 12, channels: ['phone', 'chat'], active: true },
  { agentId: 15, groupId: 13, channels: ['phone', 'chat'], active: true },
  { agentId: 15, groupId: 14, channels: ['phone'], active: true },
  { agentId: 16, groupId: 2, channels: ['phone'], active: true },
  { agentId: 16, groupId: 3, channels: ['phone'], active: true },
  { agentId: 16, groupId: 7, channels: ['phone'], active: false },
  { agentId: 16, groupId: 8, channels: ['phone'], active: true },
  { agentId: 16, groupId: 12, channels: ['phone'], active: true },
];
