/*
 * Public API Surface of @smartcontact-hub/components
 *
 * Preset (capa 6) + frontera de setup `provideSmartContactUi()` + los wrappers
 * `sc-*` (port Mitad B completo). Referencia: ../README.md y ../../AGENTS.md.
 */
export * from './lib/core/types/button.types';
export * from './lib/core/types/badge.types';
export * from './lib/core/types/theme-component.types';
export * from './lib/core/types/label.types';
export * from './lib/core/types/datatable.types';
export * from './lib/components/button/sc-button.component';
export * from './lib/components/badge/sc-badge.component';
export * from './lib/components/card/sc-card.component';
export * from './lib/components/chip/sc-chip.component';
export * from './lib/components/tag/sc-tag.component';
export * from './lib/components/message/sc-message.component';
export * from './lib/components/panel/sc-panel.component';
export * from './lib/components/skeleton/sc-skeleton.component';
export * from './lib/components/textarea/sc-textarea.component';
export * from './lib/components/drawer/sc-drawer.component';
export * from './lib/components/progressbar/sc-progressbar.component';
export * from './lib/components/progressspinner/sc-progressspinner.component';
export * from './lib/components/radiobutton/sc-radiobutton.component';
export * from './lib/components/avatar/sc-avatar.component';
export * from './lib/components/avatar/sc-avatargroup.component';
export * from './lib/components/toast/sc-toast.component';
export * from './lib/components/toast/sc-toast.service';
export * from './lib/components/divider/sc-divider.component';
export * from './lib/components/inputgroup/sc-inputgroup.component';
export * from './lib/components/search/sc-search.component';
export * from './lib/components/datepicker/sc-datepicker.component';
export * from './lib/components/inputnumber/sc-inputnumber.component';
export * from './lib/components/multiselect/sc-multiselect.component';
export * from './lib/components/group-popover/sc-group-popover.component';
export * from './lib/components/column-selector/sc-column-selector.component';
export * from './lib/components/confirmdialog/sc-confirmdialog.component';
export * from './lib/components/confirmdialog/sc-confirm.service';
export * from './lib/components/inputtext/sc-inputtext.component';
export * from './lib/components/select/sc-select.component';
export * from './lib/components/toggleswitch/sc-toggleswitch.component';
export * from './lib/components/dialog/sc-dialog.component';
export * from './lib/components/dynamic-dialog/sc-dynamic-dialog.service';
export * from './lib/components/checkbox/sc-checkbox.component';
export * from './lib/components/empty-state/sc-empty-state.component';
export * from './lib/components/page-header/sc-page-header.component';
export * from './lib/components/form-section-nav/sc-form-section-nav.component';
export * from './lib/components/bulk-edit-menu/sc-bulk-edit-menu.component';
export * from './lib/components/bulk-action-bar/sc-bulk-action-bar.component';
export * from './lib/components/bulk-action-bar/use-bulk-entity-i18n';
export * from './lib/components/form-danger-zone/sc-form-danger-zone.component';
export * from './lib/components/sticky-form-header/sc-sticky-form-header.component';
export * from './lib/components/impact-preview-dialog/sc-impact-preview-dialog.component';
export * from './lib/components/delete-entity-dialog/sc-delete-entity-dialog.component';
export * from './lib/components/color-dot-picker/sc-color-dot-picker.component';
export * from './lib/components/photo-upload/sc-photo-upload.component';
export * from './lib/components/command-palette/sc-command-palette.component';
export * from './lib/components/command-palette/sc-command-palette.service';
export * from './lib/components/keyboard-shortcuts/sc-keyboard-shortcuts.component';
export * from './lib/components/keyboard-shortcuts/sc-keyboard-shortcuts.service';
export * from './lib/components/inline-rename-cell/sc-inline-rename-cell.component';
export * from './lib/components/datatable/sc-datatable.component';
export * from './lib/components/bulk-transcription-modal/sc-bulk-transcription-modal.component';
export * from './lib/components/section-card/sc-section-card.component';
export * from './lib/components/subsection/sc-subsection.component';
export * from './lib/components/slot/sc-slot.component';
export * from './lib/core/avatar-illustration';
export * from './lib/core/utils/is-typing-target';
export * from './lib/core/services/sc-clipboard.service';
export * from './lib/config/provide-smartcontact-ui';
export { default as scPreset } from './lib/theme/sc-preset';
